spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

  datasource:
    url: jdbc:mysql://mysql-db:3306/gestion_users_roles?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: user
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

  endpoint:
    prometheus:
      enabled: true

  metrics:
    export:
      prometheus:
        enabled: true
