spring:
  datasource:
    url: jdbc:mysql://mysql:3306/gestion_users_roles?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: user
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
