apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:
      containers:
        - name: backend
          image: europe-west1-docker.pkg.dev/gestion-users-roles/devops-repo/backend:1.5

          ports:
            - containerPort: 8080

          # 👇 ICI C’EST LA BONNE PLACE
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql:3306/gestion_users_roles
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              value: root
